require 'site'

--[[--
 simple demonstration of a json RPC server.  
 Provides methods "print", "add", and "msgcheck".
 "msgcheck" demonstrates handling a JSON-RPC message in an alternate Nylon cord
 by sending a message to a second cord and returning the response generated by
 that cord.
--]]--

local Nylon = require 'nylon.core'()

local jsonrpc = require 'jsonrpc'

local testcord = Nylon.cord('althandler', function(cord)
                           for m in cord:messages() do
                               if m.msgcheck then
                                  m.returnvalue{ original = m.msgcheck, additional = 2.7182818284 }
                               end
                            end
                         end)

jsonrpc.create_listener( '*', 5001, {
             print = function(...)
                        print("PRINT:", ...)
                        return 3.14159
                     end,
             add = function( a, b )
                      local sum = a + b
                      print( "ADD:", a, b, "=", sum)
                      return sum
                   end,
             msgcheck = function(thing)
                           local rc
                           print( 'MSGCHECK:' .. tostring(thing) )
                           Nylon.self:sleep_manual(function(wake)
                                                      testcord:msg{ msgcheck = thing,
                                                         returnvalue=function(v)
                                                                        rc = v
                                                                        wake()
                                                                     end }
                                                   end)
                           return rc
                        end
          });

Nylon.run()
