message(" CMAKE_ARGS ${GLOBAL_THIRDPARTY_LIB_ARGS}")

ExternalProject_Add(nylon
   PREFIX nylon
   DEPENDS luabind
   SOURCE_DIR ${CMAKE_SOURCE_DIR}/src
   CMAKE_ARGS
      ${GLOBAL_THIRDPARTY_LIB_ARGS}
      -DLUA_ROOT=${LUA_ROOT}
      -DBUILD_SHARED=TRUE
      -DEXT_INSTALL_PATH=${EXT_INSTALL_PATH}
      -DCMAKE_INSTALL_PREFIX=${EXT_INSTALL_PATH}/nylon
)

